# This file was generated by GoReleaser. DO NOT EDIT.
cask "iconkit" do
  version "0.0.5"

  on_macos do
    on_intel do
      url "https://github.com/Tendo33/iconkit/releases/download/v#{version}/iconkit_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/Tendo33/iconkit"
      sha256 "6061d76977afad2eb63fe787c3dad5393a67758be7f6718f068a06099e58de20"
    end
    on_arm do
      url "https://github.com/Tendo33/iconkit/releases/download/v#{version}/iconkit_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/Tendo33/iconkit"
      sha256 "131a737246df23af4deca011c2b6cba0885899a9424db65ef9c2405e28ee73f8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Tendo33/iconkit/releases/download/v#{version}/iconkit_#{version}_linux_amd64.tar.gz",
        verified: "github.com/Tendo33/iconkit"
      sha256 "256440a2792dbfe18a06d89903e361b1f34e05f039858536724ada58b3099bae"
    end
    on_arm do
      url "https://github.com/Tendo33/iconkit/releases/download/v#{version}/iconkit_#{version}_linux_arm64.tar.gz",
        verified: "github.com/Tendo33/iconkit"
      sha256 "d6492bfbebdeccb6380d5f876c9b6806580e36ad4656dac23efa285ce4f54143"
    end
  end

  name "iconkit"
  desc "Developer-friendly CLI tool for icon processing - resize and round corners in one command"
  homepage "https://github.com/Tendo33/iconkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iconkit"

  # No zap stanza required

  caveats <<~EOS
    iconkit is currently distributed as an unsigned binary.
    If macOS blocks the executable, run:
      xattr -dr com.apple.quarantine "$(brew --prefix)/Caskroom/iconkit/latest/iconkit"
  EOS
end
