# This file was generated by GoReleaser. DO NOT EDIT.
cask "iconkit" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "f1402384ce7c08849657e9fa3fac8f6b059882a677dc82fc4f315d4d6e7c17f3"
      url "https://github.com/Tendo33/iconkit/releases/download/v#{version}/iconkit_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/Tendo33/iconkit"
    end
    on_arm do
      sha256 "44ad29015b58ee3b65a2adad1ac88559c8a0ac3743c97274c383839259ba52bd"
      url "https://github.com/Tendo33/iconkit/releases/download/v#{version}/iconkit_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/Tendo33/iconkit"
    end
  end

  on_linux do
    on_intel do
      sha256 "4e2cb80fe206b4e0ca35bbcf8b8bd9f53a69b5076ee4431c5900b840f5330e5c"
      url "https://github.com/Tendo33/iconkit/releases/download/v#{version}/iconkit_#{version}_linux_amd64.tar.gz",
        verified: "github.com/Tendo33/iconkit"
    end
    on_arm do
      sha256 "b20f3849602cbbaeedfc8ba96643eb88da5c71dd42b29aff482d78ef407e09b2"
      url "https://github.com/Tendo33/iconkit/releases/download/v#{version}/iconkit_#{version}_linux_arm64.tar.gz",
        verified: "github.com/Tendo33/iconkit"
    end
  end

  name "iconkit"
  desc "Developer-friendly CLI tool for icon processing - resize and round corners in one command"
  homepage "https://github.com/Tendo33/iconkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iconkit"

  # No zap stanza required

  caveats <<~EOS
    iconkit is currently distributed as an unsigned binary.
    If macOS blocks the executable, run:
      xattr -dr com.apple.quarantine "$(brew --prefix)/Caskroom/iconkit/latest/iconkit"
  EOS
end
