# This file was generated by GoReleaser. DO NOT EDIT.
cask "iconkit" do
  version "0.0.4"

  on_macos do
    on_intel do
      url "https://github.com/Tendo33/iconkit/releases/download/v#{version}/iconkit_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/Tendo33/iconkit"
      sha256 "e7922963d1a886416dd45538852b66a82a121f92e6e6b2917f09d1c91b5026ea"
    end
    on_arm do
      url "https://github.com/Tendo33/iconkit/releases/download/v#{version}/iconkit_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/Tendo33/iconkit"
      sha256 "8310a1b5f1013f6e5bf78107c9cd24657c49bd999ccb9a49d955d2203b25ac6f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Tendo33/iconkit/releases/download/v#{version}/iconkit_#{version}_linux_amd64.tar.gz",
        verified: "github.com/Tendo33/iconkit"
      sha256 "304e5433c465eb3be8dc27e30da44a845767bb204d51db3d8cf2ccfadda15fa2"
    end
    on_arm do
      url "https://github.com/Tendo33/iconkit/releases/download/v#{version}/iconkit_#{version}_linux_arm64.tar.gz",
        verified: "github.com/Tendo33/iconkit"
      sha256 "576448018a712714aa1dba987a4b1e0e3f2b65deda4e00e6740ad70cb9cde2b5"
    end
  end

  name "iconkit"
  desc "Developer-friendly CLI tool for icon processing - resize and round corners in one command"
  homepage "https://github.com/Tendo33/iconkit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iconkit"

  # No zap stanza required

  caveats <<~EOS
    iconkit is currently distributed as an unsigned binary.
    If macOS blocks the executable, run:
      xattr -dr com.apple.quarantine "$(brew --prefix)/Caskroom/iconkit/latest/iconkit"
  EOS
end
